---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории #конкретная функция интернет-магазина ИМ
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д. #мало конкретики, что подразумевает и т.д. необходим закрытый перечень критериев для фильтрации
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре. #конкретная функция товара, из формулировки не ясно что относится к подробной информации
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы #удобство не является функцией интернет-магазина 
  - Сайт должен быть безопасным и защищать данные пользователя #тестирование безопасности
  - Сайт должен иметь мобильную версию. #противоречие с ТЗ, в котором указывается, что необходима адаптивная верстка
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров #кросс-браузерное тестирование, нет конкретики какие именно браузеры необходимо тестировать
  - Сайт должен быть способен обрабатывать большое количество трафика. #тестирование производительности, но опять же что понимается под большим количеством трафика
  - Сайт должен быть доступен на различных устройствах. #дублирование требования, можно было сформулировать проще адаптивная верстка, это требование уже включает в себя и мобильные устройства и иные гаджеты. 
implicit:
  - пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге #есть в ТЗ отсутствует в требованиях
  - пользователь может оформить заказ с переходом на страницу оплаты #есть в ТЗ и отсутствует в требованиях, это сама суть интернет-магазина, весь функционал магазина не несет в себе никакого смысла если в конечном итоге покупка не будет оплачена, и заказчик не получит своих денег
  - магазин — это SPA приложение #есть в ТЗ отсутствует в требованиях
  - упоминание о политике конфиденциальности
  - мультиязычность #на какую ЦА рассчитан данный магазин, необходимы ли несколько языков
  - авторизация и регистрация пользователя #в какой момент мы получаем данные о пользователе
